var bannaPrice=12;
console.log(bannaPrice);
var seenAfter=21;
console.log( typeof seenAfter);
var name="Mizanur Rahman";
console.log(typeof name);
var isHot=true;
var isRich=false;


var promise ="I promise I will WORK hard to became a programmer";
 console.log(promise.split(' '));
 var number1=25;
 var number2=15.5;
 console.log(number1+number2);
 var number1=25;
 var number2='15.5';
 number2=parseFloat(number2);
 console.log(number1+number2);
var number1=0.1;
var number2=0.2;
var total =number1+number2;
total = total.toFixed(1);
console.log(total);
var number=-5;
var absulateNumber=Math.abs(number);
console.log(number);
var number=5.54;
var result=Math.round(number);
console.log(result);
var number=5.54;
var result=Math.ceil(number);
console.log(result);
var number=5.54;
var result=Math.floor(number);
console.log(result);
var number=Math.random()*100;
var result=Math.round(number);
console.log(result);